CREATE TABLE NODE 
(
  ID NUMBER NOT NULL 
, G_ID NUMBER NOT NULL 
, NUMB NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, INFO VARCHAR2(200 BYTE) 
, X FLOAT(126) NOT NULL 
, Y FLOAT(126) NOT NULL 
, CONSTRAINT NODE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX NODE_PK ON NODE (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE NODE
ADD CONSTRAINT NODE_FK1 FOREIGN KEY
(
  G_ID 
)
REFERENCES GRAPH
(
  ID 
)
ON DELETE CASCADE ENABLE;
