CREATE OR REPLACE PROCEDURE NEW_GRAPH 
(
  OUT_ID IN OUT NUMBER 
, IN_NAME IN VARCHAR2 
, IN_LAST_CHANGE IN DATE,
, IN_INFO IN VARCHAR2 
) AS 
BEGIN
  IF OUT_ID = 0 THEN 
    OUT_ID := SEQ_GRAPH_ID.nextval();
  END IF;
  INSERT INTO GRAPH
  VALUES(OUT_ID, IN_NAME, IN_LAST_CHANGE, IN_INFO);
END NEW_NODE;